### ISSUE TITLE
Usage Readme?

### ISSUE THREAD

**Issue by SBejga** [Cosmo/bashtv#1]
Heyho,

die pulshackdays sind vorbei und ich wollte euer cooles bashtv projekt noch ausprobieren. Ich bin leider nicht so ganz fit was swift Projekte außerhalb von xcode/ios angeht. 

Könnt ihr kurz erklären wie ich das projekt baue und ausführe?
Benötige ich den bashtv-service auch noch?

Danke und Gruß ;-)

**Comment by Marcocanc** [comment]
https://github.com/Cosmo/bashtv/commit/dcfad8eccb0e08efda74116a93b536795df24d69

**Comment by Marcocanc** [comment]
Hi!
`bashtv-service` wandelt nur die Mediatheken daten in ein flaches json um, welches dann auf github gepusht wird.
